<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="GS-5241" name="apitest.test" tests="11" failures="1" timestamp="15 Aug 2020 14:13:12 GMT" time="43.060" errors="0">
  <testcase name="verifyEmailUID" time="0.819" classname="apitest.test">
    <failure type="java.lang.AssertionError" message="expected [null] but found [21]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [21]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:132)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at apitest.test.verifyEmailUID(test.java:138)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- verifyEmailUID -->
  <testcase name="putmethodjson" time="1.424" classname="apitest.test"/>
  <testcase name="verifyGetUserStatusCode" time="0.513" classname="apitest.test"/>
  <testcase name="verifyEmailUID" time="1.066" classname="apitest.test">
    <skipped/>
  </testcase> <!-- verifyEmailUID -->
  <testcase name="verifyEmailUIDheaders" time="0.733" classname="apitest.test"/>
  <testcase name="verifyEmailUID" time="0.657" classname="apitest.test">
    <skipped/>
  </testcase> <!-- verifyEmailUID -->
  <testcase name="postMethodValidationDataFile" time="26.952" classname="apitest.test"/>
  <testcase name="verifyEmailUID2" time="1.011" classname="apitest.test"/>
  <testcase name="verifyStatusCodeDelete" time="0.851" classname="apitest.test"/>
  <testcase name="postmethodjson" time="5.096" classname="apitest.test"/>
  <testcase name="postmethodwithpojoclass" time="3.938" classname="apitest.test"/>
</testsuite> <!-- apitest.test -->
